### ISSUE TITLE
Better errors when indi_awsutils not found

### ISSUE THREAD

**Issue by carolFrohlich** [preprocessed-connectomes-project/quality-assessment-protocol#46]
Tell the user to run pip install when awsutils is not found instead of throwing the error.

**Comment by sgiavasis** [comment]
A requirements.txt has been added to the project which should handle this. Will need to test this a little bit more vigorously just prior to release.

**Comment by sgiavasis** [comment]
From @jpellman :
"For the next QAP PyPi deployment we could add the Python requirements as dependencies as well so that people don't have to download them separately."

We should re-establish what the required packages are and make sure the requirements.txt and the setup.py REQUIRES/INSTALL_REQUIRES flags are accurate.

**Comment by sgiavasis** [comment]
QAP will now automatically check for INDI-Tools and pip install it if it isn't there- whether you are installing from a cloned Github repo or via pip install.
