### ISSUE TITLE
efc_max calculation has typo?

### ISSUE THREAD

**Issue by gdevenyi** [preprocessed-connectomes-project/quality-assessment-protocol#48]
I was examining https://github.com/preprocessed-connectomes-project/quality-assessment-protocol/blob/master/qap/spatial_qc.py#L158-L186 to implement such a measure in the minc toolchain, and I couldn't quite understand where it came from, so I went back to Atkinson 1997 and tried to derive efc_max.

It looks like there was a copy-paste error, which the `1.0 / np.sqrt(np.prod(anat_data.shape))` ended up inside the np.log, where it should just be `np.log(np.sqrt(np.prod(anat_data.shape)))`

**Comment by ccraddock** [comment]
Hello Gabriel,

I am not sure that I agree, are you saying this because there is no -1 at
the beginning of the EFCmax calculation?

From the paper, for max entropy the energy would be spread evenly amongst
all of the voxels so Bj = 1. In this case Bmax=sqrt(X_Y_Z) in which X, Y,
and Z are the size of the images dimensions. Bj/Bmax = 1/sqrt(X_Y_Z).

Then, EFCmax = -1 \* Sum_1^XYZ [ 1/sqrt(XYZ)_log(1/sqrt(XYZ)) ], which
reduces to -1 \* (X_Y_Z)_1/sqrt(XYZ)*log(1/sqrt(XYZ)).

We then calculate EFC/EFCmax and since both of these contain the -1, it
cancels out, so we just dropped it from the calculation of both EFC and
EFCmax.

Does this follow your derivation, or am I off somewhere?

-cc

On Wed, Feb 10, 2016 at 3:03 PM, Gabriel A. Devenyi <
notifications@github.com> wrote:

> I was examining
> https://github.com/preprocessed-connectomes-project/quality-assessment-protocol/blob/master/qap/spatial_qc.py#L158-L186
> to implement such a measure in the minc toolchain, and I couldn't quite
> understand where it came from, so I went back to Atkinson 1997 and tried to
> derive efc_max.
> 
> It looks like there was a copy-paste error, which the 1.0 /
> np.sqrt(np.prod(anat_data.shape)) ended up inside the np.log, where it
> should just be np.log(np.sqrt(np.prod(anat_data.shape)))
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/preprocessed-connectomes-project/quality-assessment-protocol/issues/48
> .

## 

Director of Imaging, Center for the Developing Brain, Child Mind Institute
http://childmind.org
Director, Computational NeuroImaging Lab
http://computational-neuroimaging-lab.org/, Nathan S. Kline Institute for
Psychiatric Research http://www.rfmh.org/nki/
Co-Founder, The Neuro Bureau http://neurobureau.org
Impact Story https://impactstory.org/CameronCraddock
Google Scholar Citations
http://scholar.google.com/citations?user=lZ9hwSsAAAAJ&hl=en
GitHub https://github.com/ccraddock
Share that Brain @ the International Neuroimaging Datasharing Initiative
http://fcon_1000.projects.nitrc.org/!
Join me 2015-10-23 @ Brainhack Americas http://brainhack.org/Americas/!
The GigaScience Brainhack Thematic Series
http://brainhack.org/brainhack-thematic-series-call-for-papers/ is open
for your submission.

**Comment by gdevenyi** [comment]
I will do a clean derivation on paper to scan and post so we're not limited
by python syntax.

**Comment by gdevenyi** [comment]
Here's my attempt at a derivation, the difference I see is that my log is log(sqrt(S)) instead of log(1/sqrt(S))

![derivation](https://cloud.githubusercontent.com/assets/3001850/13016310/d05789c8-d18b-11e5-8757-3bb0d30c34d2.jpg)

**Comment by ccraddock** [comment]
Is this just a different form of the same equation? If you calculated it
both ways would you get a difference?

On Friday, February 12, 2016, Gabriel A. Devenyi notifications@github.com
wrote:

> Here's my attempt at a derivation, the difference I see is that my log is
> log(sqrt(S)) instead of log(1/sqrt(S))
> 
> [image: derivation]
> https://cloud.githubusercontent.com/assets/3001850/13016310/d05789c8-d18b-11e5-8757-3bb0d30c34d2.jpg
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/preprocessed-connectomes-project/quality-assessment-protocol/issues/48#issuecomment-183440969
> .

## 

Director of Imaging, Center for the Developing Brain, Child Mind Institute
http://childmind.org
Director, Computational NeuroImaging Lab
http://computational-neuroimaging-lab.org/, Nathan S. Kline Institute for
Psychiatric Research http://www.rfmh.org/nki/
Co-Founder, The Neuro Bureau http://neurobureau.org
Impact Story https://impactstory.org/CameronCraddock
Google Scholar Citations
http://scholar.google.com/citations?user=lZ9hwSsAAAAJ&hl=en
GitHub https://github.com/ccraddock
Share that Brain @ the International Neuroimaging Datasharing Initiative
http://fcon_1000.projects.nitrc.org/!
Join me 2015-10-23 @ Brainhack Americas http://brainhack.org/Americas/!
The GigaScience Brainhack Thematic Series
http://brainhack.org/brainhack-thematic-series-call-for-papers/ is open
for your submission.

**Comment by gdevenyi** [comment]
Yup, it gives the same result. Sorry for the noise.
