### ISSUE TITLE
Files overwritten when running temporal and spatial analysis in the same output directory

### ISSUE THREAD

**Issue by jhuguetn** [preprocessed-connectomes-project/quality-assessment-protocol#66]
I tend to reuse working & output directories (since I also reuse configuration file) when running temporal and spatial analysis on fMRI. 
I have discovered that some output files (mainly nipype graph, mosaic composition and some other files) are identically named in both analysis, thus when running one analysis just after the other in the same destination I got some files overwritten. 

Although is not a blocking issue, would be great to have some logic behind to avoid overwriting the existing output files when running both pipelines at once.

Jordi

**Comment by sgiavasis** [comment]
Hi Jordi,

These issues are being addressed in an upcoming release, v1.0.8. However, I will take one more close look to ensure there are no other auxiliary info files like these that are being clobbered. Thank you for the input!

Steve

**Comment by sgiavasis** [comment]
Good news- the PDF reports no longer get clobbered in 1.0.8.

However, the Nipype graphs still get overwritten with the start of each new group of participants that get run through the pipeline. If I have all of these write out as different filenames to preserve all of them, we can potentially see a very large pool of .dots/.pngs being written especially with large runs where there could be 50+ bundles.

Also, due to the nature of how we build our workflows in QAP, if a lot of participants are included simultaneously, we can see a dependency graph with a large number of parallel workflows all in one graph, which might result in very large png files. Combine this with many individual graphs and it can scale up pretty dramatically, which may not be worth it considering the fact that most of these graphs will be redundant.

However, if all three types of QAP measures are included in one run (anatomical, functional spatial, and functional temporal), the last Nipype graph to be written to (or overwritten into) the .dot/.png file may not include all of these three distinct pipelines. Also, when a pipeline is re-run, and some of the nodes do not run because they are already complete, then the graph changes to only include what happens downstream. Overwriting this into the graph file would remove previous information.

@ccraddock , any thoughts on where to go with this? I was thinking I can put in something that would maybe graph out an example of each type of workflow (as they are available) and stop afterwards.

**Comment by jhuguetn** [comment]
Great Steven, many thanks! 

BTW,when you guys plan to formally release 1.0.8?

**Comment by sgiavasis** [comment]
Hi @jhuguetn ,

We estimate next week - we will announce it in the support forum when it happens.
